
name: "CLA Assistant"
on:
  pull_request:
    types: [opened,synchronize]
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
    - name: "CLA Assistant"
      uses: ibakshay/action-template@releases/v4
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }} 
      with: 
        pathToClaSignatures: 'signatures/cla.json'
        pathToCLADocument: 'https://github.com/ibakshay/test-action-workflow/blob/master/cla.md'
        branch: 'master'

