name: "git"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
    
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test the startwith
      if: startsWith(github.ref, 'refs/tags')
      run: echo akshay
    - name: test for PR
      if: github.ref == 'refs/heads/master'
      run: echo becky
    - name: print the event name
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "${{ github.ref}}"

    - name: rebase release branch from master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git checkout release
        git fetch
        git rebase $GITHUB_SHA
        git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git fetch
        git log -${1:-25} --all --graph --decorate --abbrev-commit --pretty=oneline
