name: "git"
on:
  push:
    
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: rebase release branch from master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git remote add origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git remote set-url origin git@github.com:ibakshay/test-action-workflow.git
        git checkout release
        git rebase $GITHUB_SHA
        git push 
