name: "git"
on:
  push:
    
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: rebase release branch from master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git clone git@github.com:ibakshay/test-action-workflow.git
        git checkout release
        git fetch
        git rebase $GITHUB_SHA
        git push origin release
