
name: "CLA Assistant"
on:
  issues:
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: "TEST ACTION"
      #if: github.event.action == 'opened' || github.event.action == 'synchronize'
      uses: damccorm/issue-greeter@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
       # pathtocla: 'cla.json'
        #branch: 'master'
       repo-token: ${{ secrets.GITHUB_TOKEN }} 
